### ISSUE TITLE
Viet Bui - Software Engineering Intern - Summer 2021

### ISSUE THREAD

**Issue by vietbuiminh** [chrislevn/CodersHelpCoders#5]
[Resume Link](https://drive.google.com/file/d/108rR-p5KkgV6C_xxAvHS7mjVnkNs_LRW/view?usp=sharing)
[Job's Description](https://careers.google.com/jobs/results/113278709634343622/)

**Comment by iampauladdai** [comment]
I will get back to you in 2 days.

**Comment by chrislevn** [comment]
Ok good.

**Comment by vietbuiminh** [comment]
ok thanks!
